### ISSUE TITLE
[TODO] Balance Craft Cost Values and Items Used In Craft

### ISSUE THREAD

**Issue by TheKye** [TheKye/EcoMods#1]
- [x] Balance The Crafting Costs to use X amount of Dyes or Paint

- [x] Wood Carts to use Dyes
- [x] Other Vehicles to use Paint

**Comment by TheKye** [comment]
Powered Carts All Done - and Now use EM Resolvers to allow for editability

**Comment by TheKye** [comment]
Done!
